name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gha-mergify-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Mergify CI
        uses: Mergifyio/gha-mergify-ci@v25
        with:
          # Optional inputs:
          # token: ${{ secrets.MERGIFY_TOKEN }}
          # junit-process: 'true'
          # scopes: 'true'
